version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/instance # Ensure DB persists but don't overwrite from local
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
